package iterator

type OfBool = Of[bool]
type OfByte = Of[byte]
type OfFloat32 = Of[float32]
type OfFloat64 = Of[float64]
type OfInt = Of[int]
type OfInt32 = Of[int32]
type OfInt64 = Of[int64]
type OfRune = Of[rune]
type OfString = Of[string]

type OfBoolSlice = Of[[]bool]
type OfByteSlice = Of[[]byte]
type OfFloat32Slice = Of[[]float32]
type OfFloat64Slice = Of[[]float64]
type OfIntSlice = Of[[]int]
type OfInt32Slice = Of[[]int32]
type OfInt64Slice = Of[[]int64]
type OfRuneSlice = Of[[]rune]
type OfStringSlice = Of[[]string]
